const API_ACTION = {
    API_PENDING: 'API_PENDING',
    API_SUCCESS: 'API_SUCCESS',
    API_ERROR: 'API_ERROR',
}

const HIGHLIGHT_ACTION_TYPES = {
    ...API_ACTION
};

const CATEGORIES_ACTION_TYPES = {
    ...API_ACTION
};
 
export {HIGHLIGHT_ACTION_TYPES, CATEGORIES_ACTION_TYPES};